version: "3"
services:
  image-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - AWS_BUCKET=test
      - AWS_KEY=dummy
      - AWS_SECRET=dummy123
      - AWS_ENDPOINT=http://storage:9000
      - AWS_PATH_STYLE=true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    networks:
      - webnet
  storage:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=dummy
      - MINIO_SECRET_KEY=dummy123
    networks:
      - webnet
    command: server /data
networks:
  webnet: